name: "E-Paper WYSIWYG"
slug: e_paper_wysiwyg
description: "WYSIWYG layout editor for e-paper dashboards"
version: "0.1.2"
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
ingress: true
ingress_port: 8099
homeassistant_api: true
hassio_api: true
options:
  verbose_logging: false
schema:
  verbose_logging: bool
